# Generated by Django 3.2.4 on 2021-07-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, default='...', max_length=200)),
                ('last_name', models.CharField(blank=True, default='...', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetasIncomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MetasCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('streak', models.BooleanField(blank=True)),
                ('streak_count', models.IntegerField(blank=True, default=0)),
                ('streak_max', models.IntegerField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
    ]
