# Generated by Django 3.2.4 on 2021-07-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Edição', max_length=100)),
                ('description', models.TextField(default='Description....')),
                ('number', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, default='...', max_length=100)),
                ('last_name', models.CharField(blank=True, default='...', max_length=100)),
                ('icon', models.CharField(blank=True, default='🙂', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('edition', models.ManyToManyField(to='bot.Edition')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='MetasIncomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.edition')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MetasCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('streak', models.BooleanField(blank=True)),
                ('streak_count', models.IntegerField(blank=True, default=0)),
                ('streak_max', models.IntegerField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.edition')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
    ]
