# Generated by Django 3.2.4 on 2021-07-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True, unique=True)),
                ('title', models.CharField(default='Edition', max_length=100)),
                ('description', models.TextField(default='Description....')),
                ('active', models.BooleanField(default=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True, unique=True)),
                ('title', models.CharField(default='Level', max_length=100)),
                ('description', models.TextField(default='Description....')),
                ('points', models.IntegerField(default=0)),
                ('metas', models.IntegerField(blank=True, default=1)),
                ('metas_pro', models.IntegerField(blank=True, default=1)),
                ('prestige', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('id_user', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, default='...', max_length=100)),
                ('last_name', models.CharField(blank=True, default='...', max_length=100)),
                ('icon', models.CharField(blank=True, default='🙂', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.edition')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ManyToManyField(to='bot.Edition')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='DoneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.FloatField(blank=True, default=0)),
                ('metas_pro', models.FloatField(blank=True, default=0)),
                ('streak', models.BooleanField(blank=True)),
                ('streak_count', models.IntegerField(blank=True, default=0)),
                ('streak_max', models.IntegerField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.edition')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
            ],
        ),
    ]
