# Generated by Django 3.2.4 on 2021-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default='Level 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
