# Generated by Django 3.2.4 on 2021-07-15 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='ranking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='title',
            field=models.CharField(default='Edition', max_length=100),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
