# Generated by Django 3.2.4 on 2021-07-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210720_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='title',
            field=models.CharField(default='Edition 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default='Nvl 0. Legionário', max_length=100),
        ),
        migrations.CreateModel(
            name='LevelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.level')),
            ],
        ),
    ]
