# Generated by Django 3.2.4 on 2021-07-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210721_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveluser',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile'),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.level'),
        ),
    ]
