# Generated by Django 3.2.4 on 2021-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210722_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveluser',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
